modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/bernie-g/geckolib/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="http://geckolib.com/"
logoFile="geckolib.png" 
credits="${mod_authors}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.geckolib]]
    modId="forge"
    mandatory=true 
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.geckolib]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"